# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: '3.1'
services:
  chrome:
    image: selenium/standalone-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
          - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ghs
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
